################################################################################
# Automatically-generated file. Do not edit!
################################################################################

I_SRCS := 
S_SRCS := 
ASM_UPPER_SRCS := 
CPCP_SRCS := 
ASM_SRCS := 
C_SRCS := 
MCS_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
I_DEPS := 
PCP_S := 
EXECUTABLES := 
OBJS := 
C_DEPS := 
CPCP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
0_Src/AppSw/Tricore/APP \
0_Src/AppSw/Tricore/Driver \
0_Src/AppSw/Tricore/User \
0_Src/BaseSw/Infra/Platform/Tricore/Compilers \
0_Src/BaseSw/Service/CpuGeneric/If \
0_Src/BaseSw/Service/CpuGeneric/StdIf \
0_Src/BaseSw/Service/CpuGeneric/SysSe/Bsp \
0_Src/BaseSw/Service/CpuGeneric/SysSe/Comm \
0_Src/BaseSw/Service/CpuGeneric/SysSe/General \
0_Src/BaseSw/Service/CpuGeneric/SysSe/Math \
0_Src/BaseSw/Service/CpuGeneric/SysSe/Time \
0_Src/BaseSw/iLLD/TC26B/Tricore/Asclin/Asc \
0_Src/BaseSw/iLLD/TC26B/Tricore/Asclin/Lin \
0_Src/BaseSw/iLLD/TC26B/Tricore/Asclin/Spi \
0_Src/BaseSw/iLLD/TC26B/Tricore/Asclin/Std \
0_Src/BaseSw/iLLD/TC26B/Tricore/Ccu6/Icu \
0_Src/BaseSw/iLLD/TC26B/Tricore/Ccu6/PwmBc \
0_Src/BaseSw/iLLD/TC26B/Tricore/Ccu6/PwmHl \
0_Src/BaseSw/iLLD/TC26B/Tricore/Ccu6/Std \
0_Src/BaseSw/iLLD/TC26B/Tricore/Ccu6/TPwm \
0_Src/BaseSw/iLLD/TC26B/Tricore/Ccu6/Timer \
0_Src/BaseSw/iLLD/TC26B/Tricore/Ccu6/TimerWithTrigger \
0_Src/BaseSw/iLLD/TC26B/Tricore/Cif/Cam \
0_Src/BaseSw/iLLD/TC26B/Tricore/Cif/Std \
0_Src/BaseSw/iLLD/TC26B/Tricore/Cpu/CStart \
0_Src/BaseSw/iLLD/TC26B/Tricore/Cpu/Irq \
0_Src/BaseSw/iLLD/TC26B/Tricore/Cpu/Std \
0_Src/BaseSw/iLLD/TC26B/Tricore/Cpu/Trap \
0_Src/BaseSw/iLLD/TC26B/Tricore/Dma/Dma \
0_Src/BaseSw/iLLD/TC26B/Tricore/Dma/Std \
0_Src/BaseSw/iLLD/TC26B/Tricore/Dsadc/Dsadc \
0_Src/BaseSw/iLLD/TC26B/Tricore/Dsadc/Rdc \
0_Src/BaseSw/iLLD/TC26B/Tricore/Dsadc/Std \
0_Src/BaseSw/iLLD/TC26B/Tricore/Dts/Dts \
0_Src/BaseSw/iLLD/TC26B/Tricore/Dts/Std \
0_Src/BaseSw/iLLD/TC26B/Tricore/Emem/Std \
0_Src/BaseSw/iLLD/TC26B/Tricore/Eray/Eray \
0_Src/BaseSw/iLLD/TC26B/Tricore/Eray/Std \
0_Src/BaseSw/iLLD/TC26B/Tricore/Eth/Phy_Pef7071 \
0_Src/BaseSw/iLLD/TC26B/Tricore/Eth/Std \
0_Src/BaseSw/iLLD/TC26B/Tricore/Fce/Crc \
0_Src/BaseSw/iLLD/TC26B/Tricore/Fce/Std \
0_Src/BaseSw/iLLD/TC26B/Tricore/Fft/Fft \
0_Src/BaseSw/iLLD/TC26B/Tricore/Fft/Std \
0_Src/BaseSw/iLLD/TC26B/Tricore/Flash/Std \
0_Src/BaseSw/iLLD/TC26B/Tricore/Gpt12/IncrEnc \
0_Src/BaseSw/iLLD/TC26B/Tricore/Gpt12/Std \
0_Src/BaseSw/iLLD/TC26B/Tricore/Gtm/Atom/Pwm \
0_Src/BaseSw/iLLD/TC26B/Tricore/Gtm/Atom/PwmHl \
0_Src/BaseSw/iLLD/TC26B/Tricore/Gtm/Atom/Timer \
0_Src/BaseSw/iLLD/TC26B/Tricore/Gtm/Std \
0_Src/BaseSw/iLLD/TC26B/Tricore/Gtm/Tim/In \
0_Src/BaseSw/iLLD/TC26B/Tricore/Gtm/Tom/Pwm \
0_Src/BaseSw/iLLD/TC26B/Tricore/Gtm/Tom/PwmHl \
0_Src/BaseSw/iLLD/TC26B/Tricore/Gtm/Tom/Timer \
0_Src/BaseSw/iLLD/TC26B/Tricore/Gtm/Trig \
0_Src/BaseSw/iLLD/TC26B/Tricore/Hssl/Hssl \
0_Src/BaseSw/iLLD/TC26B/Tricore/Hssl/Std \
0_Src/BaseSw/iLLD/TC26B/Tricore/I2c/I2c \
0_Src/BaseSw/iLLD/TC26B/Tricore/I2c/Std \
0_Src/BaseSw/iLLD/TC26B/Tricore/Iom/Driver \
0_Src/BaseSw/iLLD/TC26B/Tricore/Iom/Std \
0_Src/BaseSw/iLLD/TC26B/Tricore/Msc/Msc \
0_Src/BaseSw/iLLD/TC26B/Tricore/Msc/Std \
0_Src/BaseSw/iLLD/TC26B/Tricore/Mtu/Std \
0_Src/BaseSw/iLLD/TC26B/Tricore/Multican/Can \
0_Src/BaseSw/iLLD/TC26B/Tricore/Multican/Std \
0_Src/BaseSw/iLLD/TC26B/Tricore/Port/Io \
0_Src/BaseSw/iLLD/TC26B/Tricore/Port/Std \
0_Src/BaseSw/iLLD/TC26B/Tricore/Psi5/Psi5 \
0_Src/BaseSw/iLLD/TC26B/Tricore/Psi5/Std \
0_Src/BaseSw/iLLD/TC26B/Tricore/Psi5s/Psi5s \
0_Src/BaseSw/iLLD/TC26B/Tricore/Psi5s/Std \
0_Src/BaseSw/iLLD/TC26B/Tricore/Qspi/SpiMaster \
0_Src/BaseSw/iLLD/TC26B/Tricore/Qspi/SpiSlave \
0_Src/BaseSw/iLLD/TC26B/Tricore/Qspi/Std \
0_Src/BaseSw/iLLD/TC26B/Tricore/Scu/Std \
0_Src/BaseSw/iLLD/TC26B/Tricore/Sent/Sent \
0_Src/BaseSw/iLLD/TC26B/Tricore/Sent/Std \
0_Src/BaseSw/iLLD/TC26B/Tricore/Smu/Std \
0_Src/BaseSw/iLLD/TC26B/Tricore/Src/Std \
0_Src/BaseSw/iLLD/TC26B/Tricore/Stm/Std \
0_Src/BaseSw/iLLD/TC26B/Tricore/Stm/Timer \
0_Src/BaseSw/iLLD/TC26B/Tricore/Vadc/Adc \
0_Src/BaseSw/iLLD/TC26B/Tricore/Vadc/Std \
0_Src/BaseSw/iLLD/TC26B/Tricore/_Impl \
0_Src/BaseSw/iLLD/TC26B/Tricore/_Lib/DataHandling \
0_Src/BaseSw/iLLD/TC26B/Tricore/_Lib/InternalMux \
0_Src/BaseSw/iLLD/TC26B/Tricore/_PinMap \
. \

